[#ftl]
[#macro appNS]http://www.w3.org/2007/app[/#macro] 
[#macro atomNS]http://www.w3.org/2005/Atom[/#macro]
[#macro cmisNS]http://www.cmis.org/2008/05[/#macro]
[#macro alfNS]http://www.alfresco.org[/#macro]
[#macro opensearchNS]http://a9.com/-/spec/opensearch/1.1/[/#macro]
[#macro serviceNS]xmlns="[@appNS/]" xmlns:atom="[@atomNS/]" xmlns:cmis="[@cmisNS/]" [#-- TODO: custom ns xmlns:alf="[@alfNS/]" --][/#macro]
[#macro feedNS]xmlns="[@atomNS/]" xmlns:app="[@appNS/]" xmlns:cmis="[@cmisNS/]" [#-- xmlns:alf="[@alfNS/]" xmlns:opensearch="[@opensearchNS/]" --][/#macro]
[#macro entryNS]xmlns="[@atomNS/]" xmlns:app="[@appNS/]" xmlns:cmis="[@cmisNS/]" [#-- xmlns:alf="[@alfNS/]" --][/#macro]