<html>
  <head>
    <style type="text/css">
      body
      {
      font-family: Tahoma, Arial, Helvetica, sans-serif;
      background-color: white;
      font-size: 11px;
      }

      .name {
      color: #003366;
      font-weight: bold;
      margin-right: 10px;
      }

    </style>
    <title>Simple Test</title>
  </head>
  <body>
    <div>Generated by simple-test.ftl</div>
    <div style="line-height: 25px;">
      <span class="name">Captured string value:</span> 
      <span>${simple.string}</span>
    </div>
  </body>
</html>
