version: 2
registries:
  maven-repository-artifacts-alfresco-com-nexus-content-groups-int:
    type: maven-repository
    url: https://artifacts.alfresco.com/nexus/content/groups/internal
    username: ${{secrets.NEXUS_USERNAME}}
    password: ${{secrets.NEXUS_PASSWORD}}
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
    timezone: "Europe/London"
# disabling versions updates, when set to 0 only security updates will open
  open-pull-requests-limit: 0
  allow:
    - dependency-type: "direct"
  ignore:
  - dependency-name: "org.alfresco:alfresco-audit-storage-*"
  registries:
    - maven-repository-artifacts-alfresco-com-nexus-content-groups-int
- package-ecosystem: "docker"
  directory: "packaging/docker-alfresco/"
  schedule:
    interval: "daily"
    time: "22:00"
    timezone: "Europe/London"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    github-actions:
      patterns:
        - "*"

#For 25.N
- package-ecosystem: maven
  directory: "/"
  target-branch: "release/25.N"
  schedule:
    interval: daily
    time: "22:00"
    timezone: "Europe/London"
  # disabling versions updates, when set to 0 only security updates will open
  open-pull-requests-limit: 0
  allow:
    - dependency-type: "direct"
  ignore:
    - dependency-name: "org.alfresco:alfresco-audit-storage-*"
  registries:
    - maven-repository-artifacts-alfresco-com-nexus-content-groups-int
- package-ecosystem: "github-actions"
  directory: "/"
  target-branch: "release/25.N"
  schedule:
    interval: "weekly"
  groups:
    github-actions:
      patterns:
        - "*"
