version: 2
registries:
  maven-repository-artifacts-alfresco-com-nexus-content-groups-int:
    type: maven-repository
    url: https://artifacts.alfresco.com/nexus/content/groups/internal
    username: ${{secrets.NEXUS_USERNAME}}
    password: ${{secrets.NEXUS_PASSWORD}}
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
    timezone: "Europe/London"
# disabling versions updates, when set to 0 only security updates will open
  open-pull-requests-limit: 0
  allow:
    - dependency-type: "direct"
  groups:
    spring:
      patterns:
        - "org.springframework*"
    opensearch:
      patterns:
        - "org.opensearch*"
    camel:
      patterns:
        - "org.apache.camel*"
    jackson-core:
      patterns:
        - "com.fasterxml.jackson.core*"
    bouncycastle:
      patterns:
        - "org.bouncycastle*"
  registries:
    - maven-repository-artifacts-alfresco-com-nexus-content-groups-int

- package-ecosystem: "docker"
  directory: "packaging/docker-alfresco/"
  schedule:
    interval: "weekly"
    time: "22:00"
    timezone: "Europe/London"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    github-actions:
      patterns:
        - "*"
  labels:
    - "Master"
    - "GHA"
  commit-message:
    prefix: "[GHA - Master]"

#For 25.N
- package-ecosystem: "github-actions"
  directory: "/"
  target-branch: "release/25.N"
  schedule:
    interval: "weekly"
  groups:
    github-actions:
      patterns:
        - "*"
  labels:
    - "25.N"
    - "GHA"
  commit-message:
    prefix: "[GHA - 25.N]"

#For 23.N
- package-ecosystem: "github-actions"
  directory: "/"
  target-branch: "release/23.N"
  schedule:
    interval: "weekly"
  groups:
    github-actions:
      patterns:
        - "*"
  labels:
    - "23.N"
    - "GHA"
  commit-message:
    prefix: "[GHA - 23.N]"
