@startuml

Title: Mix of AMQP and JMS Messaging Clients

actor "User\n" as U
participant "Python App\n(Apache Qpid App)" as PA
participant "Simple File Share" as SFS
participant "API Gateway" as AG
participant "Repository Service" as RS
participant "File Topic" as FT
database "Content Repository" as CR

autonumber
PA->FT: Subscribe to Topic
U->SFS: Uploads a File
activate SFS
SFS->AG: HTTP POST\nFile
activate AG
AG->RS: HTTP POST\nStore file
activate RS
RS->CR: Store file
activate CR
CR->RS: File stored
deactivate CR
RS->FT: Write message (JMS)
activate FT
note right of FT
alf-file-upload-message
end note
FT->RS: Message written
deactivate FT
RS->AG: 200 Content uploaded
deactivate RS
AG->SFS: 200 Content created
deactivate AG
SFS->U: File uploaded
deactivate SFS

group Message Processed\nBy Python App
autonumber 8
PA->FT: Read Message (AMQP)
note right of FT
alf-file-upload-message
end note
activate FT
FT->PA: Message content
deactivate FT
PA->PA: Process message
PA->FT: wait on next message (AMQP)
end

@enduml