@startuml

Title: Flow for Model Creation Message

actor "User\n" as U
participant "Model Manager App" as MMA
participant "API Gateway" as AG
participant "Search Service" as SS
participant "Model Service" as MS
participant "Repository Service" as RS
participant "Model Topic" as MT
database "Solr Index" as SI
database "Content Repository" as CR
database "Model Database" as MD

autonumber
U->MMA: Creates a New Content Model
activate MMA
MMA->AG: HTTP POST\nStore model
activate AG
AG->MS: HTTP POST\nStore model
activate MS
MS->MD: Store model
activate MD
note right of MD
NoSQL Database
end note
MD->MS: Model stored
deactivate MD
MS->MT: Write message
activate MT
note right of MT
alf-model-created-message
end note
MT->MS: Message written
deactivate MT
MS->AG: 201 Content created
deactivate MS
AG->MMA: 201 Content created
deactivate AG
MMA->U: Model created
deactivate MMA

group Message Processed\nBy Repository Service
autonumber 7
RS->MT: Read message
activate MT
note right of MT
alf-model-created-message
end note
MT->RS: Message content
deactivate MT
RS->RS: Process model
RS->CR: Store model
activate CR
CR->RS: Model stored
deactivate CR
end

group Message Processed\nBy Search Service
autonumber 7
SS->MT: Read message
activate MT
note right of MT
alf-model-created-message
end note
MT->SS: Message content
deactivate MT
SS->SS: Process model
SS->SI: Store model
activate SI
SI->SS: Model stored
deactivate SI
end


@enduml