repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
  - repo: local
    hooks:
      - id: check-format-and-headers
        name: Check format and headers and fix if necessary
        entry: ./scripts/hooks/check-format-and-headers.sh
        language: script
        files: ".*.java"
        pass_filenames: false
