jobs:
  include:
    - name: "Community Publish to S3 Release Bucket"
      stage: Publish
      if: commit_message =~ /\[community release .*\]/ AND commit_message =~ /\[publish\]/
      before_script: source scripts/set-release-variables.sh
      script: skip
      before_deploy: bash scripts/zip-artifacts-release.sh "community"
      deploy:
        - provider: s3
          access_key_id: ${RELEASE_AWS_ACCESS_KEY}
          secret_access_key: $RELEASE_AWS_ACCESS_SECRET}
          region: "eu-west-1"
          bucket: "eu.dl.alfresco.com"
          upload_dir: "release/community/RM/${RELEASE_VERSION}"
          skip_cleanup: true
          acl: private
          local_dir: artifacts_dir
          on:
            all_branches: true
      after_deploy:
        - echo "Finished release and deployed to https://s3.console.aws.amazon.com/s3/buckets/eu.dl.alfresco.com/release/community/RM/${RELEASE_VERSION}"

    - name: "Enterprise Publish to S3 Release Bucket"
      stage: Publish
      if: commit_message =~ /\[enterprise release .*\]/ AND commit_message =~ /\[publish\]/
      before_script: source scripts/set-release-variables.sh
      script: skip
      before_deploy: bash scripts/zip-artifacts-release.sh "enterprise"
      deploy:
        - provider: s3
          access_key_id: ${RELEASE_AWS_ACCESS_KEY}
          secret_access_key: ${RELEASE_AWS_ACCESS_SECRET}
          region: "eu-west-1"
          bucket: "eu.dl.alfresco.com"
          upload_dir: "release/enterprise/RM/${RELEASE_VERSION}"
          skip_cleanup: true
          acl: private
          local_dir: artifacts_dir
          on:
            all_branches: true
      after_deploy:
        - echo "Finished release and deployed to https://s3.console.aws.amazon.com/s3/buckets/eu.dl.alfresco.com/release/enterprise/RM/${RELEASE_VERSION}"
