@startuml

left to right direction
skinparam linetype ortho

rectangle "Internal Directory Configuration" {
 actor User as U1
 database "Interna]\nDirectory\n(e.g. NoSQL)" as D1
 rectangle "Identity Service" as IS1
 rectangle "Alfresco" as ALF1
 rectangle "Activiti" as ACT1
 U1---->ACT1
 U1---->ALF1
 ACT1---->IS1
 ALF1---->IS1
 IS1--->D1
}

rectangle "External Directory Configuration" {
 actor User as U2
 database "External\nDirectory\n(e.g. LDAP)" as D2a
 database "Configuration\nData\n(e.g. NoSQL)" as D2b
 rectangle "Identity Service" as IS2
 rectangle "Alfresco" as ALF2
 rectangle "Activiti" as ACT2
 U2---->ACT2
 U2---->ALF2
 ACT2---->IS2
 ALF2---->IS2
 IS2--->D2a
 IS2--->D2b
}

rectangle "External Directory Configuration with SAML" {
 actor User as U3
 database "External\nDirectory\n(e.g. LDAP)" as D3a
  database "Configuration\nData\n(e.g. NoSQL)" as D3b
 rectangle "Identity Service" as IS3
 rectangle "Alfresco" as ALF3
 rectangle "Activiti" as ACT3
 rectangle "SAML\nIdentity\nProvider" as IDP
 U3---->ACT3
 U3---->ALF3
 ACT3---->IS3
 ALF3---->IS3
 IS3-->IDP
 IDP-->D3a
 IS3-->D3b
}









@enduml