@startuml

@startuml

Title: Creating an Alfresco User

actor "End User\n <newuser>" as U
actor "Administrator\n" as A
participant "Admin Console" as AC
participant "API Gateway" as AG
participant "Identity Service" as IS
participant "User Topic" as UT
database "Directory\nNoSQL" as D
note left of U
The user created in this flow is an 'internal user', that is
one that is entirely managed by Alfresco Content Services
and not known to a Directory Service such as LDAP
end note
U->A: Request account via email
A->AC: create User
activate AC
AC->AG: HTTP POST /users/<newuser>
activate AG
note left of AG
public API
end note
AG->IS: HTTP POST ?identity service
note left of IS
internal API
end note
activate IS
IS->D: store the user account
activate D
D->IS: ok
deactivate D
IS->UT: AMQP POST userCreated message
activate UT
UT->IS: Message posted confirmation
deactivate UT
IS->AG: 201 created
deactivate IS
AG->AC: 201 created
deactivate AG
AC->A: user created\nconfirmation message
deactivate AC
A->U: Account created\nconfirmation email
@enduml



@enduml
