@startuml

@startuml

Title: OAuth Flow

actor "End User" as U
participant "Alfresco App" as ALF
participant "External System" as EXT
participant "OAuth Gateway Component" as OG
participant "API Gateway" as AG
participant "Identity Service" as IS
participant "User Topic" as UT
database "Directory\nNoSQL" as D

U->ALF: Login
activate U
ALF->AG: HTTP authn user (URL?)
activate AG
note right of AG
public API
end note
AG->IS: HTTP authn user (URL?)
note right of IS
internal API
end note
activate IS
IS->D: Retrieve user account
activate D
D->IS: Return user and validate creds
deactivate D
IS->UT: AMQP POST userLogin message
activate UT
UT->IS: Message posted confirmation
deactivate UT
IS->AG: Return token
deactivate IS
AG->ALF: Return token
deactivate AG
ALF->U: Render Page
deactivate U

U->ALF: Authorize external system
activate U
ALF->OG: Authorize external system
activate OG
OG->EXT: Redirect browser
activate EXT
EXT->U: External Login / App Auth Page
U->EXT: Login / Approve App
EXT->OG: Redirect w/ authz code
OG->EXT: Get OAuth tokens
EXT->OG: Return OAuth tokens
deactivate EXT
OG->AG: HTTP POST\n/users/{id}/identities/{extsysid}/tokens
activate AG
note right of AG
public API
end note
AG->IS: HTTP POST\n/users/{id}/identities/{extsysid}/tokens
note right of IS
internal API
end note
activate IS
IS->D: Store OAuth tokens
activate D
D->IS: ok
deactivate D
IS->UT: AMQP POST userTokenStored message
activate UT
UT->IS: Message posted confirmation
deactivate UT
IS->AG: 201 created
deactivate IS
AG->OG: 201 created
deactivate AG
OG->U: Success Page
deactivate OG
deactivate U

ALF->AG: HTTP GET\n/users/{id}/identities/{extsysid}/tokens
activate ALF
activate AG
note right of AG
public API
end note
AG->IS: HTTP GET\n/users/{id}/identities/{extsysid}/tokens
note right of IS
internal API
end note
activate IS
IS->D: Retrieve OAuth tokens
activate D
D->IS: Return OAuth tokens
deactivate D
IS->AG: Return OAuth tokens
deactivate IS
AG->ALF: Return OAuth tokens
deactivate AG
ALF->EXT: API call w/ OAuth tokens
activate EXT
EXT->ALF: Return external data
deactivate EXT
deactivate ALF

@enduml



@enduml
