<#ftl ns_prefixes={"alfresco", "http://www.alfresco.org/alfresco"}>
<html>
  <head>
    <style type="text/css">
	body
	{
	font-family: Tahoma, Arial, Helvetica, sans-serif;
	background-color: white;
	font-size: 11px;
	}

	.name 
	{
	color: #003366;
	font-weight: bold;
	margin-right: 10px;
	margin-top: 10px;
	}
    </style>
    <title>Simple Test</title>
  </head>
  <body>
    <div>Generated by output-method-callout.ftl</div>

    <div class="name"><#noparse>${alfresco.avm_sandbox_url}</#noparse></div>
    <span>${alfresco.avm_sandbox_url}</span>

    <div class="name"><#noparse>${alfresco.form_instance_data_file_name}</#noparse></div>
    <span>${alfresco.form_instance_data_file_name}</span>

    <div class="name"><#noparse>${alfresco.rendition_file_name}</#noparse></div>
    <span>${alfresco.rendition_file_name}</span>

    <div class="name"><#noparse>${alfresco.parent_path}</#noparse></div>
    <span>${alfresco.parent_path}</span>

    <div class="name"><#noparse>${alfresco.request_context_path}</#noparse></div>
    <span>${alfresco.request_context_path}</span>

    <div class="name"><#noparse>${alfresco.request_context_path}${simple.uri}</#noparse></div>
    <span>${alfresco.request_context_path}${simple.uri}</span>

    <div class="name"><#noparse>${alfresco._getAVMPath('foo')}</#noparse></div>
    <span>${alfresco._getAVMPath('foo')}</span>

    <div class="name"><#noparse>${alfresco._getAVMPath('/foo')}</#noparse></div>
    <span>${alfresco._getAVMPath('/foo')}</span>

    <div class="name">My value accessed using <#noparse>${simple.string}</#noparse>:</div>	
    <span>${simple.string}</span>

    <div class="name">My value accessed using <#noparse>$alfresco.parseXMLDocument(${alfresco.form_instance_data_file_name})</#noparse>:</div>
    <span>${alfresco.parseXMLDocument(alfresco.form_instance_data_file_name).string}</span>

    <div class="name">Values from xml files generated by in ${alfresco.parent_path}:</div>
    <ul>
      <#list alfresco.parseXMLDocuments('output-method-callout') as d>
	<li>
	  <div class="name">
	    <#noparse>${d["@alfresco:file_name"]} = ${d.string}</#noparse>
	  </div>
	  <span>${d["@alfresco:file_name"]} = ${d.string}</span>
	</li>
      </#list>
    </ul>
  </body>
</html>
