<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
                         xmlns:xhtml="http://www.w3.org/1999/xhtml"
                         xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                         exclude-result-prefixes="xhtml">

    <xsl:output method="html" version="4.01" encoding="UTF-8" indent="yes"
                doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN"
                doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
    <xsl:preserve-space elements="*"/>

    <xsl:variable name="my_variable">my_variable has a value</xsl:variable>
    <xsl:variable name="my_variable_as_arg">my_variable_as_arg has a value</xsl:variable>
    <xsl:template match="/">
      <html>
	<head>
	  <style type="text/css">
body
{
  font-family: Tahoma, Arial, Helvetica, sans-serif;
  background-color: white;
  font-size: 11px;
}

.name 
{
  color: #003366;
  font-weight: bold;
  margin-right: 10px;
  margin-top: 10px;
}
	  </style>
	  <title>Simple Test</title>
	</head>
	<body>
	  <div>Generated by output-method-callout.xsl</div>
	  <div class="name">My value accessed using /simple/string:</div>	
          <span><xsl:value-of select="/simple/string"/></span>
	  <div class="name">My value accessed using alfresco:getXMLDocument(<xsl:value-of select="$derived_from_file_name"/>):</div>
	  <span><xsl:value-of select="alfresco:getXMLDocument($derived_from_file_name)/simple/string"/></span>
          <div class="name">Values from xml files generated by in <xsl:value-of select="$parent_path"/>:</div>
	  <ul>
	  <xsl:for-each select="alfresco:getXMLDocuments('output-method-callout', '')/simple">
	    <li><xsl:value-of select="@alfresco:file-name"/> = <xsl:value-of select="string"/></li>
	  </xsl:for-each>
          </ul>
        </body>
      </html>
    </xsl:template>
</xsl:stylesheet>
