<html>
  <head>
    <title>Include Test</title>
  </head>
  <body>
    <div>Generated by include-test.ftl</div>
    <div>Value from template is <b>${.vars["include-test"]["in-template"]}</b></div>
    <#include "include-test-data-dictionary.ftl">
    <#include "include-test-webapp.ftl">
  </body>
</html>
