<html>
  <head>
    <title>Include Test</title>
  </head>
  <body>
    <div>Generated by include-webscript-test.ftl</div>
    <div>Value from template is <b>${.vars["include-test"]["in-template"]}</b></div>
    <#include "webscript://api/path/content/avm/{storeid}/www/avm_webapps/ROOT/include-test-webapp.ftl?ticket={ticket}">
  </body>
</html>
