<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
                xmlns:xhtml="http://www.w3.org/1999/xhtml"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xhtml">
  
    <xsl:output method="html" version="4.01" encoding="UTF-8" indent="yes"
                doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN"
                doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
    <xsl:preserve-space elements="*"/>
    <xsl:include href="include-test-data-dictionary.xsl"/>
    <xsl:include href="include-test-webapp.xsl"/>

    <xsl:template match="in-template">
      <div>Value from template is <b><xsl:value-of select="."/></b></div>
    </xsl:template>

    <xsl:template match="include-test">
      <html>
	<head>
	  <title>Include Test</title>
	</head>
	<body>
	  <div>Generated by include-test.xsl</div>
          <xsl:apply-templates select="in-template"/>
          <xsl:apply-templates select="in-data-dictionary"/>
          <xsl:apply-templates select="in-webapp"/>
        </body>
      </html>
    </xsl:template>
</xsl:stylesheet>
