package org.alfresco.repo.transfer.report;

import java.io.File;
import java.io.InputStream;
import java.util.List;

import org.alfresco.repo.transfer.Transfer;
import org.alfresco.service.cmr.repository.NodeRef;
import org.alfresco.service.cmr.transfer.TransferDefinition;
import org.alfresco.service.cmr.transfer.TransferEvent;
import org.alfresco.service.cmr.transfer.TransferTarget;

/**
 * Provides methods to create transfer report.
 */
public interface TransferReporter
{
       
    /**
     * Create a transfer report of success
     * @param transferName - the unique name of this transfer - probably based upon the time of transfer.
     * @param transfer the transfer.
     * @param target the target of the transfer
     * @param definition the definition of the transfer
     * @param events the transfer events generated by the transfer.
     * @param snapshotFile the snapshot file
     *
     * @return the node ref of the transfer report
     */
    public NodeRef createTransferReport(String transferName,
                Transfer transfer,
                TransferTarget target, 
                TransferDefinition definition, 
                List<TransferEvent> events,
                File snapshotFile
           );
    
    /**
     * Create a transfer report of failure
     * @param transferName - the unique name of this transfer - probably based upon the time of transfer.
     * @param e the exception
     * @param target the target of the transfer
     * @param definition the definition of the transfer
     * @param events
     * @param snapshotFile the snapshot file
     * @return the node ref of the transfer report
     */
    public NodeRef createTransferReport(String transferName,
                Exception e,
                TransferTarget target, 
                TransferDefinition definition, 
                List<TransferEvent> events,
                File snapshotFile
           );
    
    /**
     * Write the destination transfer report into the local repo.
     * 
     * @param transferName  the unique name of this transfer - probably based upon the time of transfer.
     * @param target the target of the transfer
     * @param tempFile the temporary file containing the contents of the destination side transfer report.
     * @return the node ref of the transfer report
     */
    public NodeRef writeDestinationReport(String transferName,
            TransferTarget target,
            File tempFile);
 
}
