--
-- Title:      Remove all JBPM related data from the database
-- Database:   PostgreSQL
-- Since:      V5.2
-- Author:     Stefan Kopf
--
-- Please contact support@alfresco.com if you need assistance with the upgrade.
--


-- Drop all foreign keys

ALTER TABLE JBPM_ACTION DROP FOREIGN KEY FK_ACTION_ACTNDEL; -- (optional)
ALTER TABLE JBPM_ACTION DROP FOREIGN KEY FK_ACTION_EVENT; -- (optional)
ALTER TABLE JBPM_ACTION DROP FOREIGN KEY FK_ACTION_EXPTHDL; -- (optional)
ALTER TABLE JBPM_ACTION DROP FOREIGN KEY FK_ACTION_PROCDEF; -- (optional)
ALTER TABLE JBPM_ACTION DROP FOREIGN KEY FK_ACTION_REFACT; -- (optional)
ALTER TABLE JBPM_ACTION DROP FOREIGN KEY FK_CRTETIMERACT_TA; -- (optional)
ALTER TABLE JBPM_DELEGATION DROP FOREIGN KEY FK_DELEGATION_PRCD; -- (optional)
ALTER TABLE JBPM_EVENT DROP FOREIGN KEY FK_EVENT_NODE; -- (optional)
ALTER TABLE JBPM_EVENT DROP FOREIGN KEY FK_EVENT_PROCDEF; -- (optional)
ALTER TABLE JBPM_EVENT DROP FOREIGN KEY FK_EVENT_TASK; -- (optional)
ALTER TABLE JBPM_EVENT DROP FOREIGN KEY FK_EVENT_TRANS; -- (optional)
ALTER TABLE JBPM_MODULEDEFINITION DROP FOREIGN KEY FK_MODDEF_PROCDEF; -- (optional)
ALTER TABLE JBPM_MODULEDEFINITION DROP FOREIGN KEY FK_TSKDEF_START; -- (optional)
ALTER TABLE JBPM_MODULEINSTANCE DROP FOREIGN KEY FK_MODINST_PRCINST; -- (optional)
ALTER TABLE JBPM_MODULEINSTANCE DROP FOREIGN KEY FK_TASKMGTINST_TMD; -- (optional)
ALTER TABLE JBPM_NODE DROP FOREIGN KEY FK_DECISION_DELEG; -- (optional)
ALTER TABLE JBPM_NODE DROP FOREIGN KEY FK_NODE_ACTION; -- (optional)
ALTER TABLE JBPM_NODE DROP FOREIGN KEY FK_NODE_PROCDEF; -- (optional)
ALTER TABLE JBPM_NODE DROP FOREIGN KEY FK_NODE_SCRIPT; -- (optional)
ALTER TABLE JBPM_NODE DROP FOREIGN KEY FK_NODE_SUPERSTATE; -- (optional)
ALTER TABLE JBPM_NODE DROP FOREIGN KEY FK_PROCST_SBPRCDEF; -- (optional)
ALTER TABLE JBPM_PROCESSDEFINITION DROP FOREIGN KEY FK_PROCDEF_STRTSTA; -- (optional)
ALTER TABLE JBPM_PROCESSINSTANCE DROP FOREIGN KEY FK_PROCIN_PROCDEF; -- (optional)
ALTER TABLE JBPM_PROCESSINSTANCE DROP FOREIGN KEY FK_PROCIN_ROOTTKN; -- (optional)
ALTER TABLE JBPM_PROCESSINSTANCE DROP FOREIGN KEY FK_PROCIN_SPROCTKN; -- (optional)
ALTER TABLE JBPM_SWIMLANE DROP FOREIGN KEY FK_SWL_ASSDEL; -- (optional)
ALTER TABLE JBPM_SWIMLANE DROP FOREIGN KEY FK_SWL_TSKMGMTDEF; -- (optional)
ALTER TABLE JBPM_SWIMLANEINSTANCE DROP FOREIGN KEY FK_SWIMLANEINST_SL; -- (optional)
ALTER TABLE JBPM_SWIMLANEINSTANCE DROP FOREIGN KEY FK_SWIMLANEINST_TM; -- (optional)
ALTER TABLE JBPM_TASK DROP FOREIGN KEY FK_TASK_ASSDEL; -- (optional)
ALTER TABLE JBPM_TASK DROP FOREIGN KEY FK_TASK_PROCDEF; -- (optional)
ALTER TABLE JBPM_TASK DROP FOREIGN KEY FK_TASK_STARTST; -- (optional)
ALTER TABLE JBPM_TASK DROP FOREIGN KEY FK_TASK_SWIMLANE; -- (optional)
ALTER TABLE JBPM_TASK DROP FOREIGN KEY FK_TASK_TASKMGTDEF; -- (optional)
ALTER TABLE JBPM_TASK DROP FOREIGN KEY FK_TASK_TASKNODE; -- (optional)
ALTER TABLE JBPM_TASK DROP FOREIGN KEY FK_TSK_TSKCTRL; -- (optional)
ALTER TABLE JBPM_TASKCONTROLLER DROP FOREIGN KEY FK_TSKCTRL_DELEG; -- (optional)
ALTER TABLE JBPM_TOKEN DROP FOREIGN KEY FK_TOKEN_NODE; -- (optional)
ALTER TABLE JBPM_TOKEN DROP FOREIGN KEY FK_TOKEN_PARENT; -- (optional)
ALTER TABLE JBPM_TOKEN DROP FOREIGN KEY FK_TOKEN_PROCINST; -- (optional)
ALTER TABLE JBPM_TOKEN DROP FOREIGN KEY FK_TOKEN_SUBPI; -- (optional)
ALTER TABLE JBPM_TRANSITION DROP FOREIGN KEY FK_TRANSITION_FROM; -- (optional)
ALTER TABLE JBPM_TRANSITION DROP FOREIGN KEY FK_TRANSITION_TO; -- (optional)
ALTER TABLE JBPM_TRANSITION DROP FOREIGN KEY FK_TRANS_PROCDEF; -- (optional)


-- Drop all tables

DROP TABLE JBPM_ACTION; -- (optional)
DROP TABLE JBPM_BYTEARRAY; -- (optional)
DROP TABLE JBPM_BYTEBLOCK; -- (optional)
DROP TABLE JBPM_COMMENT; -- (optional)
DROP TABLE JBPM_DECISIONCONDITIONS; -- (optional)
DROP TABLE JBPM_DELEGATION; -- (optional)
DROP TABLE JBPM_EVENT; -- (optional)
DROP TABLE JBPM_EXCEPTIONHANDLER; -- (optional)
DROP TABLE JBPM_JOB; -- (optional)
DROP TABLE JBPM_LOG; -- (optional)
DROP TABLE JBPM_MODULEDEFINITION; -- (optional)
DROP TABLE JBPM_MODULEINSTANCE; -- (optional)
DROP TABLE JBPM_NODE; -- (optional)
DROP TABLE JBPM_POOLEDACTOR; -- (optional)
DROP TABLE JBPM_PROCESSDEFINITION; -- (optional)
DROP TABLE JBPM_PROCESSINSTANCE; -- (optional)
DROP TABLE JBPM_RUNTIMEACTION; -- (optional)
DROP TABLE JBPM_SWIMLANE; -- (optional)
DROP TABLE JBPM_SWIMLANEINSTANCE; -- (optional)
DROP TABLE JBPM_TASK; -- (optional)
DROP TABLE JBPM_TASKACTORPOOL; -- (optional)
DROP TABLE JBPM_TASKCONTROLLER; -- (optional)
DROP TABLE JBPM_TASKINSTANCE; -- (optional)
DROP TABLE JBPM_TOKEN; -- (optional)
DROP TABLE JBPM_TOKENVARIABLEMAP; -- (optional)
DROP TABLE JBPM_TRANSITION; -- (optional)
DROP TABLE JBPM_VARIABLEACCESS; -- (optional)
DROP TABLE JBPM_VARIABLEINSTANCE; -- (optional)


--
-- Record script finish
--
DELETE FROM alf_applied_patch WHERE id = 'patch.db-V5.2-remove-jbpm-tables-from-db';
INSERT INTO alf_applied_patch
  (id, description, fixes_from_schema, fixes_to_schema, applied_to_schema, target_schema, applied_on_date, applied_to_server, was_executed, succeeded, report)
  VALUES
  (
    'patch.db-V5.2-remove-jbpm-tables-from-db', 'Removes all JBPM related tables from the database.',
    0, 10051, -1, 10052, null, 'UNKNOWN', ${TRUE}, ${TRUE}, 'Script completed'
  );