#!/usr/bin/env bash
#
# Packs the output of one full reactor build so that every downstream test job
# can restore it instead of rebuilding the reactor from source.
#
# Produces two tarballs under ${BUILD_OUTPUT_DIR}:
#
#   reactor-targets.tzst  every module's target/ directory: compiled main and
#                         test classes, generated sources, jars, wars, amps.
#   m2-alfresco.tzst      the org/alfresco subtree of the local Maven
#                         repository, i.e. the SNAPSHOT artifacts that this
#                         build installed.
#
# Counterpart: restore_build_output.sh
#
echo "======================= Starting Save Build Output ======================="
set -eo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../" && pwd)"
OUT="${BUILD_OUTPUT_DIR:-/tmp/build-output}"
ZSTD_OPTS="${BUILD_OUTPUT_ZSTD_OPTS:--3 -T0}"

mkdir -p "${OUT}"
cd "${ROOT}"

# Every reactor module's target/ directory. "-not -path" keeps nested target/
# directories (e.g. exploded webapps) from being listed a second time.
find . -type d -name target -not -path '*/target/*' | sort > "${OUT}/target-dirs.txt"
echo "Reactor target directories to pack:"
cat "${OUT}/target-dirs.txt"

# Excluded on purpose: per-job test output (regenerated by whichever job runs
# the tests) and content stores, which are large, disposable, and would
# otherwise leak state from the build job into every test job.
tar -I "zstd ${ZSTD_OPTS}" -cf "${OUT}/reactor-targets.tzst" \
    --exclude='surefire-reports' \
    --exclude='failsafe-reports' \
    --exclude='alf_data*' \
    --exclude='*.log' \
    -T "${OUT}/target-dirs.txt"

tar -I "zstd ${ZSTD_OPTS}" -cf "${OUT}/m2-alfresco.tzst" \
    -C "${HOME}" .m2/repository/org/alfresco

rm -f "${OUT}/target-dirs.txt"
ls -lh "${OUT}"

echo "====================== Finishing Save Build Output ======================="
