package org.alfresco.rest.search;

import org.alfresco.rest.core.IRestModel;
import org.alfresco.rest.core.assertion.ModelAssertion;
import org.alfresco.utility.model.TestModel;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Generated by 'gethin' on '2017-03-01 12:12' from 'Alfresco Search REST API' swagger file 
 * Generated from 'Alfresco Search REST API' swagger file
 * Base Path {@linkplain /alfresco/api/-default-/public/search/versions/1}
 */
public class RestRequestFacetSetModel extends TestModel implements IRestModel<RestRequestFacetSetModel>
{
    @Override
    public ModelAssertion<RestRequestFacetSetModel> assertThat()
    {
        return new ModelAssertion<RestRequestFacetSetModel>(this);
    }

    @Override
    public ModelAssertion<RestRequestFacetSetModel> and()
    {
        return assertThat();
    }

    @JsonProperty(value = "entry")
    RestRequestFacetSetModel model;

    @Override
    public RestRequestFacetSetModel onModel()
    {
        return model;
    }

    /**
    A label to use to identify the set
    */	        

    private String label;	    
    /**
    The start of the range
    */	        

    private String start;	    
    /**
    The end of the range
    */	        

    private String end;	    
    /**
    When true, the set will include values greater or equal to "start"
    */	        

    private boolean startInclusive = true;
    /**
    When true, the set will include values less than or equal to "end"
    */	        

    private boolean endInclusive = true;

    public String getLabel()
    {
        return this.label;
    }

    public void setLabel(String label)
    {
        this.label = label;
    }				

    public String getStart()
    {
        return this.start;
    }

    public void setStart(String start)
    {
        this.start = start;
    }				

    public String getEnd()
    {
        return this.end;
    }

    public void setEnd(String end)
    {
        this.end = end;
    }				

    public boolean isStartInclusive()
    {
        return this.startInclusive;
    }

    public void setStartInclusive(boolean startInclusive)
    {
        this.startInclusive = startInclusive;
    }				

    public boolean isEndInclusive()
    {
        return this.endInclusive;
    }

    public void setEndInclusive(boolean endInclusive)
    {
        this.endInclusive = endInclusive;
    }				
}
 
