package org.alfresco.rest.search;

import java.util.List;

import org.alfresco.rest.core.IRestModel;
import org.alfresco.rest.core.assertion.ModelAssertion;
import org.alfresco.utility.model.TestModel;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Generated by 'gethin' on '2017-03-17 13:23' from 'Alfresco Search REST API' swagger file 
 * Generated from 'Alfresco Search REST API' swagger file
 * Base Path {@linkplain /alfresco/api/-default-/public/search/versions/1}
 */
public class RestGenericBucketModel extends TestModel implements IRestModel<RestGenericBucketModel>
{
    @Override
    public ModelAssertion<RestGenericBucketModel> assertThat()
    {
        return new ModelAssertion<RestGenericBucketModel>(this);
    }

    @Override
    public ModelAssertion<RestGenericBucketModel> and()
    {
        return assertThat();
    }

    @JsonProperty(value = "entry")
    RestGenericBucketModel model;

    @Override
    public RestGenericBucketModel onModel()
    {
        return model;
    }

    /**
    The bucket label
    */	        

    private String label;	    
    /**
    The filter query you can use to apply this facet
    */	        

    private String filterQuery;	    
    /**
    An optional field for additional display information
    */	        

    private Object display;	    
    /**
    An array of buckets and values
    */	        

    private List<RestGenericMetricModel> metrics;	    
    private Object bucketInfo;
    /**
    Additional list of embedded GenericFacetResponse
    */	        

    private List<RestGenericFacetResponseModel> facets;

    public String getLabel()
    {
        return this.label;
    }

    public void setLabel(String label)
    {
        this.label = label;
    }				

    public String getFilterQuery()
    {
        return this.filterQuery;
    }

    public void setFilterQuery(String filterQuery)
    {
        this.filterQuery = filterQuery;
    }				

    public Object getDisplay()
    {
        return this.display;
    }

    public void setDisplay(Object display)
    {
        this.display = display;
    }				

    public List<RestGenericMetricModel> getMetrics()
    {
        return this.metrics;
    }

    public void setMetrics(List<RestGenericMetricModel> metrics)
    {
        this.metrics = metrics;
    }				

    public List<RestGenericFacetResponseModel> getFacets()
    {
        return this.facets;
    }

    public void setFacets(List<RestGenericFacetResponseModel> facets)
    {
        this.facets = facets;
    }

    public Object getBucketInfo()
    {
        return bucketInfo;
    }

    public void setFacetInfo(Object bucketInfo)
    {
        this.bucketInfo = bucketInfo;
    }			
    
}
 
