package org.alfresco.rest.search;

import java.util.List;

import org.alfresco.rest.core.IRestModel;
import org.alfresco.rest.core.assertion.ModelAssertion;
import org.alfresco.utility.model.TestModel;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Generated by 'gethin' on '2017-03-01 12:12' from 'Alfresco Search REST API' swagger file 
 * Generated from 'Alfresco Search REST API' swagger file
 * Base Path {@linkplain /alfresco/api/-default-/public/search/versions/1}
 */
public class RestResultBucketsModel extends TestModel implements IRestModel<RestResultBucketsModel>
{
    @Override
    public ModelAssertion<RestResultBucketsModel> assertThat()
    {
        return new ModelAssertion<RestResultBucketsModel>(this);
    }

    @Override
    public ModelAssertion<RestResultBucketsModel> and()
    {
        return assertThat();
    }

    @JsonProperty(value = "entry")
    RestResultBucketsModel model;

    @Override
    public RestResultBucketsModel onModel()
    {
        return model;
    }

    /**
    The field name or its explicit label, if provided on the request
    */	        

    private String label;	    
    /**
    An array of buckets and values
    */	        

    private List<FacetFieldBucket> buckets;

    public String getLabel()
    {
        return this.label;
    }

    public void setLabel(String label)
    {
        this.label = label;
    }				

    public List<FacetFieldBucket> getBuckets()
    {
        return this.buckets;
    }

    public void setBuckets(List<FacetFieldBucket> buckets)
    {
        this.buckets = buckets;
    }				
}
 
