package org.alfresco.rest.search;

import java.util.List;

import org.alfresco.rest.core.IRestModel;
import org.alfresco.rest.core.assertion.ModelAssertion;
import org.alfresco.utility.model.TestModel;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Generated by 'gethin' on '2017-03-23 10:41' from 'Alfresco Search REST API' swagger file 
 * Generated from 'Alfresco Search REST API' swagger file
 * Base Path {@linkplain /alfresco/api/-default-/public/search/versions/1}
 */
public class RestRequestFacetFieldsModel extends TestModel implements IRestModel<RestRequestFacetFieldsModel>
{
    @Override
    public ModelAssertion<RestRequestFacetFieldsModel> assertThat()
    {
        return new ModelAssertion<RestRequestFacetFieldsModel>(this);
    }

    @Override
    public ModelAssertion<RestRequestFacetFieldsModel> and()
    {
        return assertThat();
    }

    @JsonProperty(value = "entry")
    RestRequestFacetFieldsModel model;

    @Override
    public RestRequestFacetFieldsModel onModel()
    {
        return model;
    }

    /**
    Define specific fields on which to facet (adds SOLR facet.field and f.<field>.facet.* options)

    */	        

    private List<RestRequestFacetFieldModel> facets;

    public List<RestRequestFacetFieldModel> getFacets()
    {
        return this.facets;
    }

    public void setFacets(List<RestRequestFacetFieldModel> facets)
    {
        this.facets = facets;
    }				
}
 
