package org.alfresco.rest.search;

import org.alfresco.rest.core.IRestModel;
import org.alfresco.rest.core.assertion.ModelAssertion;
import org.alfresco.utility.model.TestModel;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Generated by 'msuzuki' on '2017-02-21 15:39' from 'Alfresco Search REST API' swagger file 
 * Generated from 'Alfresco Search REST API' swagger file
 * Base Path {@linkplain /alfresco/api/-default-/public/search/versions/1}
 */
public class RestRequestQueryModel extends TestModel implements IRestModel<RestRequestQueryModel>
{
    @Override
    public ModelAssertion<RestRequestQueryModel> assertThat()
    {
        return new ModelAssertion<RestRequestQueryModel>(this);
    }

    @Override
    public ModelAssertion<RestRequestQueryModel> and()
    {
        return assertThat();
    }

    @JsonProperty(value = "entry")
    RestRequestQueryModel model;

    @Override
    public RestRequestQueryModel onModel()
    {
        return model;
    }

    /**
    The query language in which the query is written.
    */	        

    private String language;	    
    /**
    The exact search request typed in by the user
    */	        

    private String userQuery;	    
    /**
    The query which may have been generated in some way from the userQuery
    */	        

    
    @JsonProperty(required = true)    
    private String query;	    

    public String getLanguage()
    {
        return this.language;
    }

    public void setLanguage(String language)
    {
        this.language = language;
    }				

    public String getUserQuery()
    {
        return this.userQuery;
    }

    public void setUserQuery(String userQuery)
    {
        this.userQuery = userQuery;
    }				

    public String getQuery()
    {
        return this.query;
    }

    public void setQuery(String query)
    {
        this.query = query;
    }
    
}
 
