package org.alfresco.rest.search;

import org.alfresco.rest.core.IRestModel;
import org.alfresco.rest.core.assertion.ModelAssertion;
import org.alfresco.utility.model.TestModel;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Generated by 'gethin' on '2017-03-17 13:23' from 'Alfresco Search REST API' swagger file 
 * Generated from 'Alfresco Search REST API' swagger file
 * Base Path {@linkplain /alfresco/api/-default-/public/search/versions/1}
 */
public class RestGenericMetricModel extends TestModel implements IRestModel<RestGenericMetricModel>
{
    @Override
    public ModelAssertion<RestGenericMetricModel> assertThat()
    {
        return new ModelAssertion<RestGenericMetricModel>(this);
    }

    @Override
    public ModelAssertion<RestGenericMetricModel> and()
    {
        return assertThat();
    }

    @JsonProperty(value = "entry")
    RestGenericMetricModel model;

    @Override
    public RestGenericMetricModel onModel()
    {
        return model;
    }

    /**
    The type of metric, e.g. count
    */	        

    private String type;	    
    /**
    The metric value, e.g.
    */	        

    private Object value;	    

    public String getType()
    {
        return this.type;
    }

    public void setType(String type)
    {
        this.type = type;
    }				

    public Object getValue()
    {
        return this.value;
    }

    public void setValue(Object value)
    {
        this.value = value;
    }				
}
 
