package org.alfresco.rest.search;

import java.util.List;

import org.alfresco.rest.core.IRestModel;
import org.alfresco.rest.core.assertion.ModelAssertion;
import org.alfresco.utility.model.TestModel;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Generated by 'gethin' on '2017-03-01 12:12' from 'Alfresco Search REST API' swagger file 
 * Generated from 'Alfresco Search REST API' swagger file
 * Base Path {@linkplain /alfresco/api/-default-/public/search/versions/1}
 */
public class RestRequestFacetIntervalsModel extends TestModel implements IRestModel<RestRequestFacetIntervalsModel>
{
    @Override
    public ModelAssertion<RestRequestFacetIntervalsModel> assertThat()
    {
        return new ModelAssertion<RestRequestFacetIntervalsModel>(this);
    }

    @Override
    public ModelAssertion<RestRequestFacetIntervalsModel> and()
    {
        return assertThat();
    }

    @JsonProperty(value = "entry")
    RestRequestFacetIntervalsModel model;

    @Override
    public RestRequestFacetIntervalsModel onModel()
    {
        return model;
    }

    /**
    Sets the intervals for all fields.
    */	        

    private List<RestRequestFacetSetModel> sets;	    
    /**
    Specifies the fields to facet by interval.
    */	        

    private List<FacetInterval> intervals;

    public List<RestRequestFacetSetModel> getSets()
    {
        return this.sets;
    }

    public void setSets(List<RestRequestFacetSetModel> sets)
    {
        this.sets = sets;
    }				

    public List<FacetInterval> getIntervals()
    {
        return this.intervals;
    }

    public void setIntervals(List<FacetInterval> intervals)
    {
        this.intervals = intervals;
    }				
}
 
