package org.alfresco.rest.model;

import java.util.List;

import org.alfresco.rest.core.IRestModel;
import org.alfresco.rest.core.assertion.ModelAssertion;
import org.alfresco.utility.model.TestModel;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Generated by 'Kristian.Dimitrov@hyland.com' on '2022-07-13 15:53' from 'Alfresco Content Services REST API' swagger file 
 * Generated from 'Alfresco Content Services REST API' swagger file
 * Base Path {@linkplain /alfresco/api/-default-/public/alfresco/versions/1}
 */
public class RestRuleSetBodyUpdateModel extends TestModel implements IRestModel<RestRuleSetBodyUpdateModel>
{
    @Override
    public ModelAssertion<RestRuleSetBodyUpdateModel> assertThat()
    {
        return new ModelAssertion<RestRuleSetBodyUpdateModel>(this);
    }

    @Override
    public ModelAssertion<RestRuleSetBodyUpdateModel> and()
    {
        return assertThat();
    }

    @JsonProperty(value = "entry")
    RestRuleSetBodyUpdateModel model;

    @Override
    public RestRuleSetBodyUpdateModel onModel()
    {
        return model;
    }

    /**
    An ordered list of the rule ids within the rule set.

Rules may not be added or removed from the rule set using this endpoint.

If this field is omitted then there is no change to the rule ordering.

    */	        

    private List<String> ruleIds;	    

    public List<String> getRuleIds()
    {
        return this.ruleIds;
    }

    public void setRuleIds(List<String> ruleIds)
    {
        this.ruleIds = ruleIds;
    }				
}
 
