/*
 * Copyright 2021 Alfresco Software, Ltd. All rights reserved.
 * License rights for this program may be obtained from Alfresco Software, Ltd.
 * pursuant to a written agreement and any use of this program without such an
 * agreement is prohibited.
 */
package org.alfresco.rest.model;

import java.util.Map;

import org.alfresco.rest.core.IRestModel;
import org.alfresco.rest.core.assertion.ModelAssertion;
import org.alfresco.utility.model.TestModel;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Generated by 'dedwards' on '2021-12-16 08:32' from 'Alfresco Content Services REST API' swagger file 
 * Generated from 'Alfresco Content Services REST API' swagger file
 * Base Path {@linkplain /alfresco/api/-default-/public/alfresco/versions/1}
 */
public class RestContentStorageInfoModel extends TestModel implements IRestModel<RestContentStorageInfoModel>
{
    @Override
    public ModelAssertion<RestContentStorageInfoModel> assertThat()
    {
        return new ModelAssertion<RestContentStorageInfoModel>(this);
    }

    @Override
    public ModelAssertion<RestContentStorageInfoModel> and()
    {
        return assertThat();
    }

    @JsonProperty(value = "entry")
    RestContentStorageInfoModel model;

    @Override
    public RestContentStorageInfoModel onModel()
    {
        return model;
    }

    /**
    Content type property identifier (e.g. cm:content). Inside this object only colon (':') delimiter for namespace-prefix will be used.

    */	        

    @JsonProperty(required = true)    
    private String id;	    
    /**
    A map (String-String) of storage properties for given content.

    */	        

    private Map<String, String> storageProperties;	    

    public String getId()
    {
        return this.id;
    }

    public void setId(String id)
    {
        this.id = id;
    }				

    public Map<String, String> getStorageProperties()
    {
        return this.storageProperties;
    }

    public void setStorageProperties(Map<String, String> storageProperties)
    {
        this.storageProperties = storageProperties;
    }				
}
 
