package org.alfresco.rest.model;

import org.alfresco.rest.core.IRestModel;
import org.alfresco.rest.core.assertion.ModelAssertion;
import org.alfresco.utility.model.TestModel;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Generated by 'aepure' on '2017-06-29 15:31' from 'Alfresco Content Services REST API' swagger file 
 * Generated from 'Alfresco Content Services REST API' swagger file
 * Base Path {@linkplain /alfresco/api/-default-/public/alfresco/versions/1}
 */
public class RestAuditAppModel extends TestModel implements IRestModel<RestAuditAppModel>
{
    @Override
    public ModelAssertion<RestAuditAppModel> assertThat()
    {
        return new ModelAssertion<RestAuditAppModel>(this);
    }

    @Override
    public ModelAssertion<RestAuditAppModel> and()
    {
        return assertThat();
    }

    @JsonProperty(value = "entry")
    RestAuditAppModel model;

    @Override
    public RestAuditAppModel onModel()
    {
        return model;
    }

    @JsonProperty(required = true)
    private String id;

    private String name;

    private boolean isEnabled;

    public String getId()
    {
        return this.id;
    }

    public void setId(String id)
    {
        this.id = id;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public boolean getIsEnabled()
    {
        return this.isEnabled;
    }

    public void setIsEnabled(boolean isEnabled)
    {
        this.isEnabled = isEnabled;
    }

}
