package org.alfresco.rest.model;

import org.alfresco.rest.core.IRestModel;
import org.alfresco.rest.core.assertion.ModelAssertion;
import org.alfresco.utility.model.TestModel;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Generated by 'aforascu' on '2018-01-10 16:02' from 'Alfresco Content Services REST API' swagger file 
 * Generated from 'Alfresco Content Services REST API' swagger file
 * Base Path {@linkplain /alfresco/api}
 */
public class RestLicenseInfoModel extends TestModel implements IRestModel<RestLicenseInfoModel>
{
    @Override
    public ModelAssertion<RestLicenseInfoModel> assertThat()
    {
        return new ModelAssertion<RestLicenseInfoModel>(this);
    }

    @Override
    public ModelAssertion<RestLicenseInfoModel> and()
    {
        return assertThat();
    }

    @JsonProperty(value = "entry")
    RestLicenseInfoModel model;

    @Override
    public RestLicenseInfoModel onModel()
    {
        return model;
    }


    @JsonProperty(required = true)    
    private String issuedAt;	    

    @JsonProperty(required = true)    
    private String expiresAt;	    

    @JsonProperty(required = true)    
    private int remainingDays;	    

    @JsonProperty(required = true)    
    private String holder;	    

    @JsonProperty(required = true)    
    private String mode;	    

    private RestEntitlementsInfoModel entitlements;	    

    public String getIssuedAt()
    {
        return this.issuedAt;
    }

    public void setIssuedAt(String issuedAt)
    {
        this.issuedAt = issuedAt;
    }				

    public String getExpiresAt()
    {
        return this.expiresAt;
    }

    public void setExpiresAt(String expiresAt)
    {
        this.expiresAt = expiresAt;
    }				

    public int getRemainingDays()
    {
        return this.remainingDays;
    }

    public void setRemainingDays(int remainingDays)
    {
        this.remainingDays = remainingDays;
    }				

    public String getHolder()
    {
        return this.holder;
    }

    public void setHolder(String holder)
    {
        this.holder = holder;
    }				

    public String getMode()
    {
        return this.mode;
    }

    public void setMode(String mode)
    {
        this.mode = mode;
    }				

    public RestEntitlementsInfoModel getEntitlements()
    {
        return this.entitlements;
    }

    public void setEntitlements(RestEntitlementsInfoModel entitlements)
    {
        this.entitlements = entitlements;
    }				
}
 
