package org.alfresco.rest.model;

import java.util.List;

import org.alfresco.rest.core.IRestModel;
import org.alfresco.rest.core.assertion.ModelAssertion;
import org.alfresco.utility.model.TestModel;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Generated by 'Kristian.Dimitrov@hyland.com' on '2022-07-13 15:53' from 'Alfresco Content Services REST API' swagger file 
 * Generated from 'Alfresco Content Services REST API' swagger file
 * Base Path {@linkplain /alfresco/api/-default-/public/alfresco/versions/1}
 */
public class RestLinkedRuleSetBodyCreateModel extends TestModel implements IRestModel<RestLinkedRuleSetBodyCreateModel>
{
    @Override
    public ModelAssertion<RestLinkedRuleSetBodyCreateModel> assertThat()
    {
        return new ModelAssertion<RestLinkedRuleSetBodyCreateModel>(this);
    }

    @Override
    public ModelAssertion<RestLinkedRuleSetBodyCreateModel> and()
    {
        return assertThat();
    }

    @JsonProperty(value = "entry")
    RestLinkedRuleSetBodyCreateModel model;

    @Override
    public RestLinkedRuleSetBodyCreateModel onModel()
    {
        return model;
    }

    /**
    Identifier for either the folder or the rule set
    */	        

    @JsonProperty(required = true)    
    private String id;	    

    public String getId()
    {
        return this.id;
    }

    public void setId(String id)
    {
        this.id = id;
    }				
}
 
