package org.alfresco.rest.model;

import org.alfresco.rest.core.IRestModel;
import org.alfresco.rest.core.assertion.ModelAssertion;
import org.alfresco.utility.model.TestModel;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Generated by 'aforascu' on '2018-01-10 16:02' from 'Alfresco Content Services REST API' swagger file 
 * Generated from 'Alfresco Content Services REST API' swagger file
 * Base Path {@linkplain /alfresco/api}
 */
public class RestModuleInfoModel extends TestModel implements IRestModel<RestModuleInfoModel>
{
    @Override
    public ModelAssertion<RestModuleInfoModel> assertThat()
    {
        return new ModelAssertion<RestModuleInfoModel>(this);
    }

    @Override
    public ModelAssertion<RestModuleInfoModel> and()
    {
        return assertThat();
    }

    @JsonProperty(value = "entry")
    RestModuleInfoModel model;

    @Override
    public RestModuleInfoModel onModel()
    {
        return model;
    }


    private String id;	    

    private String title;	    

    private String description;	    

    private String version;	    

    private String installDate;	    

    private String installState;	    

    private String versionMin;	    

    private String versionMax;	    

    public String getId()
    {
        return this.id;
    }

    public void setId(String id)
    {
        this.id = id;
    }				

    public String getTitle()
    {
        return this.title;
    }

    public void setTitle(String title)
    {
        this.title = title;
    }				

    public String getDescription()
    {
        return this.description;
    }

    public void setDescription(String description)
    {
        this.description = description;
    }				

    public String getVersion()
    {
        return this.version;
    }

    public void setVersion(String version)
    {
        this.version = version;
    }				

    public String getInstallDate()
    {
        return this.installDate;
    }

    public void setInstallDate(String installDate)
    {
        this.installDate = installDate;
    }				

    public String getInstallState()
    {
        return this.installState;
    }

    public void setInstallState(String installState)
    {
        this.installState = installState;
    }				

    public String getVersionMin()
    {
        return this.versionMin;
    }

    public void setVersionMin(String versionMin)
    {
        this.versionMin = versionMin;
    }				

    public String getVersionMax()
    {
        return this.versionMax;
    }

    public void setVersionMax(String versionMax)
    {
        this.versionMax = versionMax;
    }				
}
 
