---
import:
  - source: travis/.travis.env-vars.yml
  - source: travis/.travis.tests-stage.yml
  - source: travis/.travis.integration-test-MySQL.yml
  - source: travis/.travis.deploy-stage.yml
dist: xenial
sudo: required
language: java
jdk: openjdk11

services:
  - docker

git:
  depth: false
  quiet: true

branches:
  only:
    - master
    - /release\/.*/
    - /feature\/.*/
    - /merge\/.*/
    - /hotfix\/.*/

cache:
  directories:
    - ${HOME}/.m2/repository

before_cache: rm -rf ${HOME}/.m2/repository/org/alfresco/alfresco-governance-services*

install: skip

stages:
  - name: Tests
    if: commit_message !~ /\[skip tests\]/
  - name: Deploy
    if: fork = false AND (branch = master OR branch =~ /release\/.*/) AND type != pull_request
  - name: Release
    if: fork = false AND (branch = master OR branch =~ /release\/.*/) AND type != pull_request AND commit_message =~ /\[(community|enterprise) release .*\]/
  - name: Publish
    if: fork = false AND (branch = master OR branch =~ /release\/.*/) AND type != pull_request AND commit_message =~ /\[publish\]/
