//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.cmis.org/ns/1.0", ClrNamespace="www.cmis.org.ns._1._01")]



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cmis.org/ns/1.0", ConfigurationName="NavigationServicePort")]
public interface NavigationServicePort
{
    
    // CODEGEN: Parameter 'documentAndFolderCollection' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="InvalidArgumentException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="FilterNotValidException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="RuntimeException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="PermissionDeniedException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="OperationNotSupportedException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="ConcurrencyException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="FolderNotValidException")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(repositoryInfoType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(objectTypeDefinitionType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(objectTypeBase))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="documentAndFolderCollection")]
    getDescendantsResponse getDescendants(getDescendants request);
    
    // CODEGEN: Parameter 'documentCollection' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="InvalidArgumentException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="FilterNotValidException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="RuntimeException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="PermissionDeniedException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="OperationNotSupportedException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="ConcurrencyException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="FolderNotValidException")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(repositoryInfoType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(objectTypeDefinitionType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(objectTypeBase))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="documentCollection")]
    getCheckedoutDocsResponse getCheckedoutDocs(getCheckedoutDocs request);
    
    // CODEGEN: Parameter 'folderCollection' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="InvalidArgumentException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="FilterNotValidException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="RuntimeException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="ObjectNotFoundException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="PermissionDeniedException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="OperationNotSupportedException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="ConcurrencyException")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(repositoryInfoType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(objectTypeDefinitionType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(objectTypeBase))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="folderCollection")]
    getDocumentParentsResponse getDocumentParents(getDocumentParents request);
    
    // CODEGEN: Parameter 'documentAndFolderCollection' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="InvalidArgumentException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="FilterNotValidException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="RuntimeException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="PermissionDeniedException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="OperationNotSupportedException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="ConcurrencyException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="FolderNotValidException")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(repositoryInfoType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(objectTypeDefinitionType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(objectTypeBase))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="documentAndFolderCollection")]
    getChildrenResponse getChildren(getChildren request);
    
    // CODEGEN: Parameter 'folderCollection' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="InvalidArgumentException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="FilterNotValidException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="RuntimeException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="PermissionDeniedException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="OperationNotSupportedException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="ConcurrencyException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="FolderNotValidException")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(repositoryInfoType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(objectTypeDefinitionType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(objectTypeBase))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="folderCollection")]
    getFolderParentResponse getFolderParent(getFolderParent request);
    
    // CODEGEN: Parameter 'documentCollection' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="InvalidArgumentException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="FilterNotValidException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="RuntimeException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="PermissionDeniedException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="OperationNotSupportedException")]
    [System.ServiceModel.FaultContractAttribute(typeof(object), Action="", Name="ConcurrencyException")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(repositoryInfoType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(objectTypeDefinitionType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(objectTypeBase))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="documentCollection")]
    getUnfiledDocsResponse getUnfiledDocs(getUnfiledDocs request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmis.org/ns/1.0")]
public enum typesOfObjectsEnum
{
    
    /// <remarks/>
    FoldersAndDocumets,
    
    /// <remarks/>
    Folders,
    
    /// <remarks/>
    Documents,
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getDescendants", WrapperNamespace="http://www.cmis.org/ns/1.0", IsWrapped=true)]
public partial class getDescendants
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=0)]
    public string folderId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=1)]
    public typesOfObjectsEnum type;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=2)]
    public object depth;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=3)]
    public string filter;
    
    public getDescendants()
    {
    }
    
    public getDescendants(string folderId, typesOfObjectsEnum type, object depth, string filter)
    {
        this.folderId = folderId;
        this.type = type;
        this.depth = depth;
        this.filter = filter;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getDescendantsResponse", WrapperNamespace="http://www.cmis.org/ns/1.0", IsWrapped=true)]
public partial class getDescendantsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("object", IsNullable=false)]
    public documentOrFolderObjectType[] documentAndFolderCollection;
    
    public getDescendantsResponse()
    {
    }
    
    public getDescendantsResponse(documentOrFolderObjectType[] documentAndFolderCollection)
    {
        this.documentAndFolderCollection = documentAndFolderCollection;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getCheckedoutDocs", WrapperNamespace="http://www.cmis.org/ns/1.0", IsWrapped=true)]
public partial class getCheckedoutDocs
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=0)]
    public string filter;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string maxItems;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=2)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string skipCount;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=3)]
    public string folderID;
    
    public getCheckedoutDocs()
    {
    }
    
    public getCheckedoutDocs(string filter, string maxItems, string skipCount, string folderID)
    {
        this.filter = filter;
        this.maxItems = maxItems;
        this.skipCount = skipCount;
        this.folderID = folderID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getCheckedoutDocsResponse", WrapperNamespace="http://www.cmis.org/ns/1.0", IsWrapped=true)]
public partial class getCheckedoutDocsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("object", IsNullable=false)]
    public documentObjectType[] documentCollection;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=1)]
    public bool hasMoreItems;
    
    public getCheckedoutDocsResponse()
    {
    }
    
    public getCheckedoutDocsResponse(documentObjectType[] documentCollection, bool hasMoreItems)
    {
        this.documentCollection = documentCollection;
        this.hasMoreItems = hasMoreItems;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getDocumentParents", WrapperNamespace="http://www.cmis.org/ns/1.0", IsWrapped=true)]
public partial class getDocumentParents
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=0)]
    public string documentId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=1)]
    public string filter;
    
    public getDocumentParents()
    {
    }
    
    public getDocumentParents(string documentId, string filter)
    {
        this.documentId = documentId;
        this.filter = filter;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getDocumentParentsResponse", WrapperNamespace="http://www.cmis.org/ns/1.0", IsWrapped=true)]
public partial class getDocumentParentsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("object", IsNullable=false)]
    public folderObjectType[] folderCollection;
    
    public getDocumentParentsResponse()
    {
    }
    
    public getDocumentParentsResponse(folderObjectType[] folderCollection)
    {
        this.folderCollection = folderCollection;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getChildren", WrapperNamespace="http://www.cmis.org/ns/1.0", IsWrapped=true)]
public partial class getChildren
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=0)]
    public string folderId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=1)]
    public typesOfObjectsEnum type;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=2)]
    public string filter;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=3)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string maxItems;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=4)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string skipCount;
    
    public getChildren()
    {
    }
    
    public getChildren(string folderId, typesOfObjectsEnum type, string filter, string maxItems, string skipCount)
    {
        this.folderId = folderId;
        this.type = type;
        this.filter = filter;
        this.maxItems = maxItems;
        this.skipCount = skipCount;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getChildrenResponse", WrapperNamespace="http://www.cmis.org/ns/1.0", IsWrapped=true)]
public partial class getChildrenResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("object", IsNullable=false)]
    public documentOrFolderObjectType[] documentAndFolderCollection;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=1)]
    public bool hasMoreItems;
    
    public getChildrenResponse()
    {
    }
    
    public getChildrenResponse(documentOrFolderObjectType[] documentAndFolderCollection, bool hasMoreItems)
    {
        this.documentAndFolderCollection = documentAndFolderCollection;
        this.hasMoreItems = hasMoreItems;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getFolderParent", WrapperNamespace="http://www.cmis.org/ns/1.0", IsWrapped=true)]
public partial class getFolderParent
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=0)]
    public string folderId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=1)]
    public string filter;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=2)]
    public bool returnToRoot;
    
    public getFolderParent()
    {
    }
    
    public getFolderParent(string folderId, string filter, bool returnToRoot)
    {
        this.folderId = folderId;
        this.filter = filter;
        this.returnToRoot = returnToRoot;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getFolderParentResponse", WrapperNamespace="http://www.cmis.org/ns/1.0", IsWrapped=true)]
public partial class getFolderParentResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("object", IsNullable=false)]
    public folderObjectType[] folderCollection;
    
    public getFolderParentResponse()
    {
    }
    
    public getFolderParentResponse(folderObjectType[] folderCollection)
    {
        this.folderCollection = folderCollection;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getUnfiledDocs", WrapperNamespace="http://www.cmis.org/ns/1.0", IsWrapped=true)]
public partial class getUnfiledDocs
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=0)]
    public string filter;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string maxDocuments;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=2)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string skipCount;
    
    public getUnfiledDocs()
    {
    }
    
    public getUnfiledDocs(string filter, string maxDocuments, string skipCount)
    {
        this.filter = filter;
        this.maxDocuments = maxDocuments;
        this.skipCount = skipCount;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getUnfiledDocsResponse", WrapperNamespace="http://www.cmis.org/ns/1.0", IsWrapped=true)]
public partial class getUnfiledDocsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("object", IsNullable=false)]
    public documentObjectType[] documentCollection;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cmis.org/ns/1.0", Order=1)]
    public bool hasMoreItems;
    
    public getUnfiledDocsResponse()
    {
    }
    
    public getUnfiledDocsResponse(documentObjectType[] documentCollection, bool hasMoreItems)
    {
        this.documentCollection = documentCollection;
        this.hasMoreItems = hasMoreItems;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface NavigationServicePortChannel : NavigationServicePort, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class NavigationServicePortClient : System.ServiceModel.ClientBase<NavigationServicePort>, NavigationServicePort
{
    
    public NavigationServicePortClient()
    {
    }
    
    public NavigationServicePortClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public NavigationServicePortClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NavigationServicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NavigationServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getDescendantsResponse NavigationServicePort.getDescendants(getDescendants request)
    {
        return base.Channel.getDescendants(request);
    }
    
    public documentOrFolderObjectType[] getDescendants(string folderId, typesOfObjectsEnum type, object depth, string filter)
    {
        getDescendants inValue = new getDescendants();
        inValue.folderId = folderId;
        inValue.type = type;
        inValue.depth = depth;
        inValue.filter = filter;
        getDescendantsResponse retVal = ((NavigationServicePort)(this)).getDescendants(inValue);
        return retVal.documentAndFolderCollection;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getCheckedoutDocsResponse NavigationServicePort.getCheckedoutDocs(getCheckedoutDocs request)
    {
        return base.Channel.getCheckedoutDocs(request);
    }
    
    public documentObjectType[] getCheckedoutDocs(string filter, string maxItems, string skipCount, string folderID, out bool hasMoreItems)
    {
        getCheckedoutDocs inValue = new getCheckedoutDocs();
        inValue.filter = filter;
        inValue.maxItems = maxItems;
        inValue.skipCount = skipCount;
        inValue.folderID = folderID;
        getCheckedoutDocsResponse retVal = ((NavigationServicePort)(this)).getCheckedoutDocs(inValue);
        hasMoreItems = retVal.hasMoreItems;
        return retVal.documentCollection;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getDocumentParentsResponse NavigationServicePort.getDocumentParents(getDocumentParents request)
    {
        return base.Channel.getDocumentParents(request);
    }
    
    public folderObjectType[] getDocumentParents(string documentId, string filter)
    {
        getDocumentParents inValue = new getDocumentParents();
        inValue.documentId = documentId;
        inValue.filter = filter;
        getDocumentParentsResponse retVal = ((NavigationServicePort)(this)).getDocumentParents(inValue);
        return retVal.folderCollection;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getChildrenResponse NavigationServicePort.getChildren(getChildren request)
    {
        return base.Channel.getChildren(request);
    }
    
    public documentOrFolderObjectType[] getChildren(string folderId, typesOfObjectsEnum type, string filter, string maxItems, string skipCount, out bool hasMoreItems)
    {
        getChildren inValue = new getChildren();
        inValue.folderId = folderId;
        inValue.type = type;
        inValue.filter = filter;
        inValue.maxItems = maxItems;
        inValue.skipCount = skipCount;
        getChildrenResponse retVal = ((NavigationServicePort)(this)).getChildren(inValue);
        hasMoreItems = retVal.hasMoreItems;
        return retVal.documentAndFolderCollection;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getFolderParentResponse NavigationServicePort.getFolderParent(getFolderParent request)
    {
        return base.Channel.getFolderParent(request);
    }
    
    public folderObjectType[] getFolderParent(string folderId, string filter, bool returnToRoot)
    {
        getFolderParent inValue = new getFolderParent();
        inValue.folderId = folderId;
        inValue.filter = filter;
        inValue.returnToRoot = returnToRoot;
        getFolderParentResponse retVal = ((NavigationServicePort)(this)).getFolderParent(inValue);
        return retVal.folderCollection;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getUnfiledDocsResponse NavigationServicePort.getUnfiledDocs(getUnfiledDocs request)
    {
        return base.Channel.getUnfiledDocs(request);
    }
    
    public documentObjectType[] getUnfiledDocs(string filter, string maxDocuments, string skipCount, out bool hasMoreItems)
    {
        getUnfiledDocs inValue = new getUnfiledDocs();
        inValue.filter = filter;
        inValue.maxDocuments = maxDocuments;
        inValue.skipCount = skipCount;
        getUnfiledDocsResponse retVal = ((NavigationServicePort)(this)).getUnfiledDocs(inValue);
        hasMoreItems = retVal.hasMoreItems;
        return retVal.documentCollection;
    }
}

