--
-- Title:      Fix jbpm tables
-- Database:   Generic
-- Since:      V3.3 schema 4013
-- Author:     janv
--
-- Please contact support@alfresco.com if you need assistance with the upgrade.
--
-- This script is only required to fix JBPM columns on DB2.
--
