version: "3"

# For remote debug we need the CATALINA_OPTS and to expose port 8000.

services:
    alfresco:
    # acs repo community image with ags repo community amp applied
        image: alfresco/alfresco-governance-repository-community:latest
        environment:
            CATALINA_OPTS : "
                -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
                "
            JAVA_OPTS : "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dalfresco.restApi.basicAuthScheme=true
                -Dimap.server.enabled=true
                -Dftp.enabled=true
                -Dftp.dataPortFrom=30000
                -Dftp.dataPortTo=30099
                -Dshare.host=localhost
                -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
                -Dmessaging.broker.url=\"failover:(tcp://activemq:61616)?timeout=3000&jms.useCompression=true\"

                -Dlocal.transform.service.enabled=${LOCAL_TRANSFORM_SERVICE_ENABLED}
                -DlocalTransform.pdfrenderer.url=http://alfresco-pdf-renderer:8090/
                -DlocalTransform.imagemagick.url=http://imagemagick:8090/
                -DlocalTransform.libreoffice.url=http://libreoffice:8090/
                -DlocalTransform.tika.url=http://tika:8090/
                -DlocalTransform.misc.url=http://transform-misc:8090/

                -Dlegacy.transform.service.enabled=${LEGACY_TRANSFORM_SERVICE_ENABLED}
                -Dalfresco-pdf-renderer.url=http://alfresco-pdf-renderer:8090/
                -Djodconverter.url=http://libreoffice:8090/
                -Dimg.url=http://imagemagick:8090/
                -Dtika.url=http://tika:8090/
                -Dtransform.misc.url=http://transform-misc:8090/

                -Dimap.server.port=1143
                -Dftp.port=1221
                -Dcors.enabled=true
                -Dcors.allowed.origins=http://localhost:4200
                "
        ports:
            - 8080:8080
            - 8000:8000
            - 143:1143
            - "21:21"
            - "30000-30099:30000-30099"

    alfresco-pdf-renderer:
        image: alfresco/alfresco-pdf-renderer:${TRANSFORMERS_TAG}
        environment:
            JAVA_OPTS: " -Xms256m -Xmx256m"
        ports:
            - 8090:8090

    imagemagick:
        image: alfresco/alfresco-imagemagick:${TRANSFORMERS_TAG}
        environment:
            JAVA_OPTS: " -Xms256m -Xmx256m"
        ports:
            - 8091:8090

    libreoffice:
        image: alfresco/alfresco-libreoffice:${TRANSFORMERS_TAG}
        environment:
            JAVA_OPTS: " -Xms256m -Xmx256m"
        ports:
            - 8092:8090

    tika:
        image: alfresco/alfresco-tika:${TRANSFORMERS_TAG}
        environment:
            JAVA_OPTS: " -Xms256m -Xmx256m"
        ports:
            - 8093:8090

    transform-misc:
        image: alfresco/alfresco-transform-misc:${TRANSFORMERS_TAG}
        environment:
            JAVA_OPTS: " -Xms256m -Xmx256m"
        ports:
            - 8094:8090

    postgres:
        image: library/postgres:${POSTGRES_TAG}
        environment:
            - POSTGRES_PASSWORD=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_DB=alfresco
        ports:
            - 5432:5432

    solr6:
        image: alfresco/alfresco-search-services:${SOLR6_TAG}
        environment:
            #Solr needs to know how to register itself with Alfresco
            - SOLR_ALFRESCO_HOST=alfresco
            - SOLR_ALFRESCO_PORT=8080
            #Alfresco needs to know how to call solr
            - SOLR_SOLR_HOST=solr6
            - SOLR_SOLR_PORT=8983
            #Create the default alfresco and archive cores
            - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
             #HTTP by default
            - ALFRESCO_SECURE_COMMS=none
        ports:
            - 8083:8983 #Browser port

    activemq:
        image: alfresco/alfresco-activemq:${ACTIVEMQ_TAG}
        ports:
            - 8161:8161 # Web Console
            - 5672:5672 # AMQP
            - 61616:61616 # OpenWire
            - 61613:61613 # STOMP