<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:alf="http://www.alfresco.org" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://schemas.xmlsoap.org/soap/encoding/" targetNamespace="http://www.alfresco.org"
    name="AlfrescoCMISWebServices">

    <import namespace="http://docs.oasis-open.org/ns/cmis/ws/200908/" location="CMISWS-Service.wsdl" />
    <import namespace="http://www.alfresco.org" location="Alfresco-Core.xsd" />

</definitions>