### Integration tests on MySQL are running:
##    - on stable branch
##    - on demand with commit message [execute tests on MySQL]

jobs:
  include:
  - &integration_test_on_MYSQL
    name: "Community Integrations Tests on MySQL"
    stage: Tests
    if: branch =~ /(release\/.*$|master)/ OR commit_message =~ /\[execute tests on MySQL\]/
    before_script:
      - docker run -d -p 3307:3306 -e MYSQL_ROOT_PASSWORD=alfresco -e MYSQL_USER=alfresco -e MYSQL_DATABASE=alfresco -e MYSQL_PASSWORD=alfresco  mysql:5.7.23 --transaction-isolation='READ-COMMITTED'
      - docker run -d -p 61617:61617 -p 5673:5673 alfresco/alfresco-activemq:5.15.8
    script: travis_retry travis_wait 80 mvn -B -q clean verify ${MVN_SKIP} -Puse-mysql -Dskip.integrationtests=false -Dmy.db.name=alfresco -Dmy.db.port=3307 -f rm-community/pom.xml  -amd ${LOG_WARN}

  - <<: *integration_test_on_MYSQL
    name: "Enterprise Integrations Tests on MySQL"
    install: travis_retry travis_wait 60 mvn -B -V -q clean install ${MVN_SKIP}
    script: travis_retry travis_wait 80 mvn -B -q clean verify ${MVN_SKIP} -Puse-mysql -Dskip.integrationtests=false -Dmy.db.name=alfresco -Dmy.db.port=3307 -f rm-enterprise/pom.xml -amd ${LOG_WARN}
