### Integration tests on MySQL are running:
##    - on stable branch
##    - on demand with commit message [execute tests on MySQL]

jobs:
  include:
  - &integration_test_on_MYSQL
    name: "Community Integrations Tests on MySQL"
    services: docker
    stage: Tests
    if: branch =~ /(release\/.*$|master)/ OR commit_message =~ /\[execute tests on MySQL\]/
    before_install: source ./scripts/mysql/start.sh mysql:5.6.26
    script:
      - travis_retry travis_wait 80 mvn -B -q clean install -Puse-mysql -DskipTests  -Dskip.integrationtests=false -Dmy.db.name=alfresco -Dmy.db.port=3306 -Dcommunity -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

  - <<: *integration_test_on_MYSQL
    name: "Enterprise Integrations Tests on MySQL"
    install:
      - travis_retry travis_wait 60 mvn -B -q clean install -DskipTests -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -f rm-community/pom.xml -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    script:
      - travis_retry travis_wait 80 mvn -B -q clean install -Puse-mysql -DskipTests -Dskip.integrationtests=false  -Dmy.db.name=alfresco -Dmy.db.port=3306 -f rm-enterprise/pom.xml -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
