package org.alfresco.repo.audit.generator;

import java.io.Serializable;

import org.alfresco.api.AlfrescoPublicApi;   

/**
 * Interface for Audit data value generators.These are used to produce auditable data values
 * extract auditable values from nothing; typically these values are derived from the system
 * state or from the thread context.
 * <p/>
 * <tt>null</tt> values will be ignored by the audit framework.
 * 
 * @author Derek Hulley
 * @since 3.2
 */
@AlfrescoPublicApi
public interface DataGenerator
{
    /**
     * Get the data generated by the instance.
     * 
     * @return              Returns the generated data or <tt>null</tt> if no data could be generated
     * @throws Throwable    All exceptions are handled by the framework
     */
    public Serializable getData() throws Throwable;
}
