[#ftl]
[#macro appNS]http://www.w3.org/2007/app[/#macro] 
[#macro atomNS]http://www.w3.org/2005/Atom[/#macro]
[#macro cmisNS]http://docs.oasis-open.org/ns/cmis/core/200908/[/#macro]
[#macro cmismNS]http://docs.oasis-open.org/ns/cmis/messaging/200908/[/#macro]
[#macro cmisraNS]http://docs.oasis-open.org/ns/cmis/restatom/200908/[/#macro]
[#macro alfNS]http://www.alfresco.org[/#macro]
[#macro opensearchNS]http://a9.com/-/spec/opensearch/1.1/[/#macro]
[#macro serviceNS]xmlns="[@appNS/]" xmlns:atom="[@atomNS/]" xmlns:cmisra="[@cmisraNS/]" xmlns:cmis="[@cmisNS/]" xmlns:alf="[@alfNS/]"[/#macro]
[#macro feedNS]xmlns="[@atomNS/]" xmlns:app="[@appNS/]" xmlns:cmisra="[@cmisraNS/]" xmlns:cmis="[@cmisNS/]" xmlns:alf="[@alfNS/]" xmlns:opensearch="[@opensearchNS/]"[/#macro]
[#macro entryNS]xmlns="[@atomNS/]" xmlns:app="[@appNS/]" xmlns:cmisra="[@cmisraNS/]" xmlns:cmis="[@cmisNS/]" xmlns:alf="[@alfNS/]"[/#macro]
[#macro allowableactionsNS]xmlns:cmis="[@cmisNS/]"[/#macro]
[#macro aclNS]xmlns:cmis="[@cmisNS/]"[/#macro]
