default_url=https://support.hyland.com/
root_url=https://support.hyland.com/access?dita:id=
prod_ver=&vrm_version=25.1
community_link=&component=Alfresco%20Content%20Services
enterprise_link=&component=Alfresco%20Content%20Services%20Community%20Edition

demoTopicUrl1= ${root_url}wja1720089576392${prod_ver}
demoTopicUrl2= ${root_url}wja1720089576392${prod_ver}
demoTopicUrlWithDocEdition= ${root_url}wja1720089576392${prod_ver}{0}