name: Alfresco Community Repo CI

on: push

env:
  # Both variables are required to be set before the release process starts.
  # As the release is triggered by a commit message with "[release]" keyword on a release branch,
  # setting these variables to new values can be done in the same commit and will indicate the release and the dev versions in it.
  DEVELOPMENT_VERSION: "17.92-SNAPSHOT" # The version that will be set in pom files after the release (next dev version)
  RELEASE_VERSION: "17.91" # The version of the release (tag).
  GITHUB_ACTIONS_DEPLOY_TIMEOUT: 60
  MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  TAS_SCRIPTS: ../alfresco-community-repo/packaging/tests/scripts
  TAS_ENVIRONMENT: ./packaging/tests/environment
  LOG_WARN: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
  JAVA_VERSION: "17"

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Clean cache"
        run: bash ./scripts/travis/cleanup_cache.sh
      - name: "Prepare environment"
        run: bash ./scripts/travis/prepare.sh

  veracode:
    runs-on: ubuntu-latest
    needs:
      - prepare
    steps:
      - uses: actions/checkout@v3
      - uses: Alfresco/alfresco-build-tools/.github/actions/veracode@v1.12.0
        with:
          srcclr-api-token: ${{ secrets.SRCCLR_API_TOKEN }}

  AllUnitTestsSuite:
    runs-on: ubuntu-latest
    needs:
      - prepare
    steps:
      - uses: actions/checkout@v3
      - name: "Login to Quay.io"
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: "Set up Java"
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
          cache: "maven"
      - name: "test"
        run: mvn --settings .travis.settings.xml --file pom.xml -B test -pl core,data-model -am -DfailIfNoTests=false
      - name: "test2"
        run: mvn --settings .travis.settings.xml --file pom.xml -am "-Dtest=AllUnitTestsSuite,AllMmtUnitTestSuite" -DfailIfNoTests=false
